### ISSUE TITLE
Look here for file manipulation

### ISSUE THREAD

**Issue by lablnet** [souravmondaldev/Bus-Reservation-System#2]
https://gist.github.com/Lablnet/6f135b25640bebeb1bca7ddc97ada523

**Comment by souravmondaldev** [comment]
That's a nice gist @Lablnet. Can you help me to add it to my code?

**Comment by lablnet** [comment]
> That's a nice gist @Lablnet. Can you help me to add it to my code?

Yes i can help but if you can wait

because Universtiy, my exam will starts from 13 june and ends on 20 june.

**Comment by souravmondaldev** [comment]
Sure @Lablnet
